version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    build:
      dockerfile: Dockerfile
      context: ./nginx
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - '27020:27017'
    command: --storageEngine wiredTiger
