version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [ "nginx", "-g", "daemon off;" ]
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - "27020:27017"
    command: --storageEngine wiredTiger
